server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;

    location /cstrike/maps/ {
        autoindex off;
        try_files $uri =404;
        add_header Cache-Control "public, max-age=86400";
    }

    location / {
        return 404;
    }
}
