; Maps configuration file
; File location: $moddir/addons/amxmodx/configs/maps.ini
; To use with Maps Menu plugin

; Add in your mod's maps here
; Delete this file to use mapcycle.txt

de_dust2
de_inferno
de_dust2_2x2
awp_india
35hp_2
aim_map
aim_headshot
fy_snow
fy_pool_day
cs_deathmatch-final
cs_deathmatch_2005c
